**Import all the needed libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

**Data Collection**

In [2]:
# import the dataset to pandas

df = pd.read_csv(r"C:\Users\Admin\Jupyter_Note_folder\Data Science Projects\data\heart_disease_data.csv")

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# reshuffle the dataset

df = df.sample(frac = 1, random_state = 42).reset_index(drop = True)

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,57,1,0,150,276,0,0,112,1,0.6,1,1,1,0
1,59,1,3,170,288,0,0,159,0,0.2,1,0,3,0
2,57,1,2,150,126,1,1,173,0,0.2,2,1,3,1
3,56,0,0,134,409,0,0,150,1,1.9,1,2,3,0
4,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1

In [4]:
# shape of the data

df.shape

(303, 14)

In [5]:
# information of the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [6]:
# check for missing value

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

**Data Analysis**

In [7]:
# statistical meassure of the dataset

df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [8]:
# checking the distribution of heart disease status

df["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

target label representation:
- 1 = present of heart disease
- 0 = absent of heart disease

Splitting of data into features and target

In [9]:
# store features and target in X and Y respectively

X = df.drop(columns = ["target"])
Y = df["target"]

**Model Development**

In [10]:
# splitting the dataset into training and test data

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42, stratify = Y)

In [11]:
# create the logistic model

model = LogisticRegression(max_iter = 1000, random_state = 42)

# train the model with training data

model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000, random_state=42)

**Model Evaluation**

In [12]:
# compare the prediction of the model with training data
train_y_pred = model.predict(X_train)

train_df = pd.DataFrame({
    "Actual": Y_train,
    "Prediction": train_y_pred
})

train_df.head()

     Actual  Prediction
36        1           1
184       0           0
275       0           0
272       0           0
102       1           1

In [13]:
# compare the prediction of the model with test data
test_y_pred = model.predict(X_test)

test_df = pd.DataFrame({
    "Actual": Y_test,
    "Prediction": test_y_pred
})

test_df.head()

     Actual  Prediction
31        0           0
69        0           1
268       0           0
62        0           0
54        0           0

In [14]:
# Evaluate the model performance with classification report

train_rpt = classification_report(Y_train, train_y_pred)
test_rpt = classification_report(Y_test, test_y_pred)

print(f"Training Data classification report is \n {train_rpt}")
print(f"Test Data classification report is \n {test_rpt}")

Training Data classification report is
               precision    recall  f1-score   support

           0       0.87      0.75      0.80       110
           1       0.81      0.91      0.86       132

    accuracy                           0.83       242
   macro avg       0.84      0.83      0.83       242
weighted avg       0.84      0.83      0.83       242

Test Data classification report is
               precision    recall  f1-score   support

           0       0.89      0.89      0.89        28
           1       0.91      0.91      0.91        33

    accuracy                           0.90        61
   macro avg       0.90      0.90      0.90        61
weighted avg       0.90      0.90      0.90        61